<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TBN-0R3REM" ignored="1" name="接口测试用例" tests="3" failures="1" timestamp="05 三月 2019 06:42:03 GMT" time="0.026" errors="0">
  <testcase name="testdemo1" time="0.008" classname="com.luowj.test.TestCaces">
    <failure type="java.lang.AssertionError" message="测试失败">
      <![CDATA[java.lang.AssertionError: 测试失败
	at com.luowj.test.TestCaces.testdemo1(TestCaces.java:70)
	at com.luowj.Application.main(Application.java:16)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testdemo1 -->
  <testcase name="testdeme2" time="0.0" classname="com.luowj.test.TestCaces"/>
  <testcase name="testdeme3" time="0.0" classname="com.luowj.test.TestCaces"/>
  <testcase name="test" time="0.0" classname="com.luowj.test.TestCaces">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- 接口测试用例 -->
